#!/bin/bash
apt-get update
apt-get upgrade
apt-get install git-core
apt-get install i2c-tools libi2c-dev python-smbus

cd /home/pi
git clone git://git.drogon.net/wiringPi
cd wiringPi
./build

cd /home/pi
git clone https://github.com/dimitdim/assetValue.git
cd assetValue
g++ asset.cpp -DRPI -lwiringPi -o /usr/local/bin/asset
